dependencies:
  - OpenZeppelin/openzeppelin-contracts@2.5.0
  - smartcontractkit/chainlink@1.11.0

compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@2.5.0'
      - '@chainlink=smartcontractkit/chainlink@1.11.0'

dotenv: .env

networks:
  default: development

  development:
    verify: False

  mainnet-fork:
    uni_token: '0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984'
    weth_token: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False

  goerli:
    uni_token: '0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984'
    weth_token: '0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6'
    eth_usd_price_feed: '0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e'
    verify: True




wallets:
  from_key: ${PRIVATE_KEY}